version: '3'

services:
   web:
    build: ./Urduocr
    volumes:
      - .:/Urduocr
    ports:
      - 8000:8000
    links:
      - db
      - ts

   db:
    build: "./db"
    restart: always
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: emart22
      MYSQL_PASSWORD: emart22
      MYSQL_DATABASE: ocrdev

   ts:
    build: "./tesseract"


