# Generated by Django 2.0.1 on 2018-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstproject', '0002_auto_20180712_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
